server:
  port: '8085'
  servlet:
    context-path: /movie-ticket-booking
spring:
  sql.init.mode: always
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  datasource:
    driverClassName: org.h2.Driver
    username: sa
    url: jdbc:h2:file:./data/movie-booking-db
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate.ddl-auto: update
  h2:
    console:
      enabled: true
app:
  admin:
    users: kwtmayank@gmail.com
  genres:
    RomCom: Romantic-Comedy
    Horror: Horror
    Comedy: Comedy
    Romance: Romance
    Drama: Drama
    Sci-Fi: Science-Fiction
    Action: Action
    Thriller: Thriller
logging:
  level:
    org.springframework.web: "info"
    org.hibernate: "error"