server:
  port: '8085'
  servlet:
    context-path: /movie-ticket-booking
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/movie-booking-db
  h2:
    console:
      enabled: true
app:
  admin:
    users: kwtmayank@gmail.com
  genres:
    RomCom: Romantic-Comedy
    Horror: Horror
    Comedy: Comedy
    Romance: Romance
    Drama: Drama
    Sci-Fi: Science-Fiction
    Action: Action
    Thriller: Thriller
logging:
  level:
    org.springframework.web: "info"
    org.hibernate: "error"