server:
  port: '8085'
  servlet:
    context-path: /movie-ticket-booking
spring:
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  datasource:
    driverClassName: org.h2.Driver
    username: sa
    url: jdbc:h2:file:./movie-booking-db
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
app:
  admin:
    users: kwtmayank@gmail.com
logging:
  level:
    org.springframework.web: "info"
    org.hibernate: "error"