CREATE TABLE IF NOT EXISTS USERS
(
    USER_ID INTEGER PRIMARY KEY,
    FIRST_NAME VARCHAR(200) NOT NULL,
    LAST_NAME VARCHAR(200) NOT NULL,
    EMAIL VARCHAR(200) NOT NULL,
    ROLE VARCHAR(200) NOT NULL,
    PASSWORD VARCHAR(200) NOT NULL
);